FRONTENDSCHOOL5/final-19-EggplantMarket

.vscode/settings.json
=> Docs : settings.json

css/font.css
=> design : font.css 작성

css/chat_room.css, html/chat_room.html, scss/chat_room.scss
- 마크업 구조랑 태그 사용 적절한지 확인해주세요.
- 대화 내용은 각각의 콘텐츠로 보기 위해 article을 사용했는데 다들 어떻게 생각하시나요..? 괜찮을까요?
- 대화 내용을 article로 했을 때 h2-h6까지 필요해서 h2를 사용했습니다.
- 모달창은 상단에 더보기 클릭 시 보이도록 하기 위해 지금은 주석 처리를 해두었습니다.
- 반응형 작업 시 이미지를 보낼 때 사이즈를 고정으로 할 지 변화를 줄 지 고민입니다. - 고정을 하지 않으면 이미지가 커집니다.... 음....
- 대화창 상단 부분 마크업
- 대화 내용 보여주기 마크업
- 채팅 입력 부분 마크업
- 모달창 마크업
- 버튼창 클릭 시 모달창 나오도록
=> design: 채팅방 구현

.vscode/settings.json, css/post_detail.css, html/post_detail.html, scss/post_detail.scss
* 마크업 구조랑 태그 사용 적절한지 확인 부탁드립니다
* 마크업 및 CSS (post_detail.html)
- 공통 컴포넌트 수정한 것 적용하기
- 게시물 클릭시 상세페이지로 넘어 갈 수 있게 연결
=> design : 게시글 상세페이지 마크업 및 디자인

css/post_upload.css, html/post_upload.html, scss/post_upload.scss
- 클래스 네이밍 확인해주세요
- 마크업 구조랑 태그 사용 적절한지 확인해주세요
- 파일추가로 넣은 이미지 마크업은 숨김처리(display : none)해놨어요
- 전반적인 마크업 (post_upload.html)
- JS로 입력값에 따라 TextArea 높이 자동조절 기능 구현
- JS로 file 입력 받을시 프리뷰 띄워주는 기능
=> design : 게시물 작성 업로드 마크업 및 디자인

html/join_membership.html, js/login_email.js, js/setProfile.js
=> fix : api 주소변경, 회원가입완료 후 페이지 이동, 로컬스토리지 토큰 추가

css/post_detail.css, html/post_detail.html, js/postDetail.js, scss/post_detail.scss
- 댓글 섹션 마크업 수정
- 댓글창 입력시 게시버튼 활성화
- 해당 게시글 url 쿼리스트링 받아오기
- 해당 게시글 내용 api 연결 및 데이터 뿌리기
- 해당 게시글 댓글 api 연결 및 데이터 뿌리기
- 댓글 추가 기능
- 모달창으로 댓글 삭제/신고 기능
- 날짜 
- 좋아요
=> add : 게시글 댓글 페이지 기능 구현

css/product.css, html/product.html, js/product.js, js/product_add.js, js/product_modification.js, scss/product.scss
- 상품 product-id가 없는 경우 product_add.js를 실행하고 상품 product-id가 있는 경우 product_modification.js를 실행합니다.
- 상품을 새로 등록 시 product의 id가 로컬스토리지에 product-id로 생성됩니다. 
- 상품 삭제 시 로컬스토리지에 등록된 product-id를 삭제하는 기능을 추가해야 합니다.
- 오타가 있는지 확인해주세요..!
- 상품 등록 시 작성된 데이터 전송
- 상품 id가 있는 경우 등록된 상품 정보를 가져와 수정 후 수정된 데이터 전송
- 상품 등록 시 로컬스토리지에 product의 id 정보 저장
- 상품 등록 시 값을 모두 채우면 저장 버튼 활성화
- 입력 값 유효성 검사
- 상품 등록 버튼 클릭 시 product-id가 없으므로 product_add.js 연결
- 상품 등록이 된 내역을 수정 시 product-id가 있으므로 product_modification.js 연결
- 상품 삭제 시 해당 product-id를 삭제
product-id가 없을 때
모든 값을 입력하면 버튼 활성화 -> 새로 고침 시 생성된 product-id를 통해 데이터 가져옴
=> add : 상품 정보 등록 및 수정

js/common.js, js/profile_info.js
- 클래스 네이밍 확인해주세요
- 마크업 구조랑 태그 사용 적절한지 확인해주세요
- 
- 전반적인 마크업 (.html)
- 
-
=> #39 refactor : 날짜처리 common에 옮김'

css/component.css, css/post_detail.css, html/post_detail.html, js/postDetail.js, scss/component.scss, scss/post_detail.scss
- url 쿼리스트링 연결
- 게시물 내용 보이기 (api)
- 댓글 가져오기 (api)
- 댓글 작성하면 게시 버튼 활성화
- 댓글 게시하기
=> add : 게시글 상세보기 페이지 기능 구현

css/post_upload.css, html/post_upload.html, js/postUpload.js, scss/post_upload.scss
- 
- 게시글 작성하는 사용자 프로필 이미지 가져오기
- 글이 입력되거나 사진이 업로드 되면 업로드버튼 활성화
- 버튼을 누르면 게시글 업로드
- textarea 높이 조절
- (도전) 이미지 최대 3장까지 업로드 가능
=> add : 게시글 업로드 기능 구현

js/join.js, js/login_email.js, js/postUpload.js, js/product_add.js, js/product_modification.js, js/profile_modification.js, js/setProfile.js
- 유효성 검사 전 공백이 제거되도록 코드를 입력했는데 확인해주세요...!
- 페이지 별 문자를 입력하기 전에 공백이 있으면 공백을 제거하고 입력 내용을 저장할 수 있도록 수정
- 비밀번호는 공백을 포함하기 때문에 비밀번호 input에는 공백도 입력 값으로 저장될 수 있도록 수정
=> fix : 문자 입력 전 공백 제거

js/product_add.js, js/product_modification.js, js/profile_modification.js, js/setProfile.js
- 이미지에도 trim() 메서드가 설정되어 있어 제거하였습니다.
- 이미지에 적용된 trim() 메서드 제거
-
=> chore : 이미지에 적용된 trim() 값 제거

css/chat_room.css, js/chat_room.js, scss/chat_room.scss
- x
- 채팅 입력창 padding, margin 값 주기
- 버튼 색상 변경
-
=> design : 채팅 입력창 디자인 수정 및 버튼 색상 변경

css/home_search.css, html/post_detail.html, html/product_upload.html, html/profile_info.html, js/common.js, js/follower.js, js/following.js, js/home.js, js/home_search.js, js/modal.js, js/postDetail.js, js/product_add.js, js/product_modification.js, js/profile_info.js, scss/home_search.scss
- 이미지 처리
- 이미지 확장자 검사
- 검색화면 페이지 padding bottom
- 상품가격 예외처리
- 홈, 상세페이지 좋아요 붙이기
- 전반적인 마크업 (.html)
- 
-
=> Exception(1)

css/profile_productlist.css, js/home.js, js/postDetail.js, js/profile_info.js, scss/profile_productlist.scss
- 터치 스크롤 구현
- 홈, 게시물 상세에도 이미지 여러개 보이게 수정했습니다
- 터치 스크롤 구현
- 키보드 탐색도 가능하게 기능구현하기
=> #39 add : 터치스크롤

js/common.js
- 더 좋은 방법이 생각나시면 공유해주세요..
- 백버튼 이후 페이지 reload
-
=> #61 fix : history.back 이후 reload

js/modal.js, js/postUpload.js, js/profile_info.js
- post_upload에 작성했습니다
- 코드가 지저분할수 있어요
- 게시글 수정기능
- 사진이 여러개 있는 게시글 처리하기
=> #77 add : 게시글 수정

js/common.js
- 이미지 확장자만 2개 추가했습니다
이상 없으면 바로 머지해주세요
-
=> #61 refactor : 이미지 확장자 추가

js/common.js, js/home.js, js/postUpload.js, js/profile_info.js
- 게시글 3개 업로드 기능]
- checkImg return 테마따라 조정
- 게시글 수정 추가 작업 (이미지가 여러개인 게시글)
=> #77 add : 게시글 이미지 3개 업로드 기능 

js/modal.js
- popUpModal에서 취소를 선택하면 postModal의 취소로 이동하도록 설정해두었습니다.
- tab을 이용해서 focus 설정하기
-
=> refactor: 모달창 tab 설정

html/home.html, html/home_search.html, js/home.js, js/home_search.js
- home.html / home_search.html / home.js / home_search.js 파일 변동사항 있습니다
- innerHTML 은 template 태그 변경을 위해 다시 원상복귀 해두었습니다 
- 큰 변동사항 없어서 확인후 바로 merge 해도 될 것 같습니다 :)
- 불필요한 개행, 로그 출력 삭제
- 함수명 클래스명 확인
- innerHTML 로 작성된 부분 component 리팩토링 진행하면서 template 태그로 변환하여 작업 진행하려합니다.
=> refactor : 홈 피드페이지/ 검색페이지 리펙토링

html/home.html, js/home.js, js/home_search.js
Reverts FRONTENDSCHOOL5/final-19-EggplantMarket#103
=> Revert "refactor : 홈 피드페이지/ 검색페이지 리펙토링"

js/home.js, js/profile_info.js
- 머지받아주세요 : )
- 재영님 피드백 반영하여 home.js / profile_info.js 페이지 간단한 수정 완료하였습니다.
-
=> Refactor : component 수정

html/chat_list.html, html/chat_room.html, html/home.html, html/home_search.html, html/join_membership.html, html/login.html, html/login_email.html, html/post_detail.html, html/post_upload.html, html/product_upload.html, html/profile_follower.html, html/profile_following.html, html/profile_info.html, html/profile_modification.html, index.html
=> #106 refactor : 메타태그 수정

html/chat_list.html, html/chat_room.html, html/home.html, html/home_search.html, html/join_membership.html, html/login.html, html/login_email.html, html/post_detail.html, html/post_upload.html, html/product_upload.html, html/profile_follower.html, html/profile_following.html, html/profile_info.html, html/profile_modification.html, index.html, robot.txt
=> robot.txt 추가 및 메타태그 수정

css/footer.css, scss/footer.scss
- 하단 탭 요소끼리 크기 안맞는거 조정했습니다
- 
-
=> #fix : 하단 탭 크기 맞추기

js/index.js, js/postDetail.js
- 클래스 네이밍 확인해주세요
- 마크업 구조랑 태그 사용 적절한지 확인해주세요
- 
- get('user') -> get('user-token')
-
=> splash localstorage getitem 수정
